In [1]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [3]:
%cd /content/gdrive/My Drive/Kaggle_Data/P2P lending/

/content/gdrive/My Drive/Kaggle_Data/P2P lending

In [4]:
import pandas as pd
import numpy as np

In [5]:
data =  pd.read_csv("data_1.csv",index_col=False)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
data.columns

Index(['id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'emp_title',
       ...
       'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method',
       'debt_settlement_flag', 'emp_length_int', 'term_int',
       'earliest_cr_line_date', 'mths_since_earliest_cr_line', 'issue_d_date',
       'mths_since_issue_d'],
      dtype='object', length=115)

In [8]:
data.head(3)

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,emp_length_int,term_int,earliest_cr_line_date,mths_since_earliest_cr_line,issue_d_date,mths_since_issue_d
0,68407277,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,Jan-2019,122.67,Mar-2019,564.0,560.0,0.0,1.0,Individual,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,4.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N,10,36.0,2003-08-01,172.0,2015-12-01,24.0
1,68355089,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.0,0.0,25679.660000,25679.66,24700.0,979.66,0.0,0.0,0.0,Jun-2016,926.35,Mar-2019,699.0,695.0,0.0,1.0,Individual,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,0.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N,10,36.0,1999-12-01,216.0,2015-12-01,24.0
2,68341763,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.0,0.0,22705.924294,22705.92,20000.0,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,Mar-2019,704.0,700.0,0.0,1.0,Joint App,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,10.0,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N,10,60.0,2000-08-01,208.0,2015-12-01,24.0

# Converting categorical data into dumie variables

In [9]:
data_dumies=[pd.get_dummies(data['grade'],prefix='grade',prefix_sep=':'),
             pd.get_dummies(data['sub_grade'],prefix='sub_grade',prefix_sep=':'),
             pd.get_dummies(data['home_ownership'],prefix='home_ownership',prefix_sep=':'),
             pd.get_dummies(data['verification_status'],prefix='verification_status',prefix_sep=':'),
             pd.get_dummies(data['loan_status'],prefix='loan_status',prefix_sep=':'),
             pd.get_dummies(data['purpose'],prefix='purpose',prefix_sep=':'),
             pd.get_dummies(data['addr_state'],prefix='addr_state',prefix_sep=':'),
             pd.get_dummies(data['initial_list_status'],prefix='initial_list_status',prefix_sep=':'),
             ]

In [10]:
data['hardship_flag'].value_counts()

N    2259836
Y        832
Name: hardship_flag, dtype: int64

In [11]:
data_d=pd.concat(data_dumies,axis=1)

In [12]:
data_d.shape

(2260701, 127)

In [13]:
data=pd.concat([data,data_d],axis=1)

In [14]:
data.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,emp_length_int,term_int,earliest_cr_line_date,mths_since_earliest_cr_line,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:ND,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
0,68407277,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,Mar-2019,564.0,560.0,0.0,1.0,Individual,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,4.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N,10,36.0,2003-08-01,172.0,2015-12-01,24.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,68355089,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,Mar-2019,699.0,695.0,0.0,1.0,Individual,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,0.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N,10,36.0,1999-12-01,216.0,2015-12-01,24.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2,68341763,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,Mar-2019,704.0,700.0,0.0,1.0,Joint App,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,10.0,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N,10,60.0,2000-08-01,208.0,2015-12-01,24.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,66310712,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Mar-2019,679.0,675.0,0.0,1.0,Individual,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,N,Cash,N,10,60.0,2008-09-01,111.0,2015-12-01,24.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,68476807,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,Mar-2018,704.0,700.0,0.0,1.0,Individual,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,1.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,N,Cash,N,3,60.0,1998-06-01,234.0,2015-12-01,24.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1

# **Preprocessing missing values**

In [15]:
pd.options.display.max_rows=None
data.isnull().sum()

id                                                                       0
loan_amnt                                                               33
funded_amnt                                                             33
funded_amnt_inv                                                         33
term                                                                    33
int_rate                                                                33
installment                                                             33
grade                                                                   33
sub_grade                                                               33
emp_title                                                           167002
emp_length                                                          146940
home_ownership                                                          33
annual_inc                                                              37
verification_status                                                     33
issue_d                                                                 33
loan_status                                                             33
pymnt_plan                                                              33
url                                                                     33
purpose                                                                 33
title                                                                23358
zip_code                                                                34
addr_state                                                              33
dti                                                                   1744
delinq_2yrs                                                             62
earliest_cr_line                                                        62
fico_range_low                                                          33
fico_range_high                                                         33
inq_last_6mths                                                          63
mths_since_last_delinq                                             1158535
mths_since_last_record                                             1901545
open_acc                                                                62
pub_rec                                                                 62
revol_bal                                                               33
revol_util                                                            1835
total_acc                                                               62
initial_list_status                                                     33
out_prncp                                                               33
out_prncp_inv                                                           33
total_pymnt                                                             33
total_pymnt_inv                                                         33
total_rec_prncp                                                         33
total_rec_int                                                           33
total_rec_late_fee                                                      33
recoveries                                                              33
collection_recovery_fee                                                 33
last_pymnt_d                                                          2460
last_pymnt_amnt                                                         33
last_credit_pull_d                                                     105
last_fico_range_high                                                    33
last_fico_range_low                                                     33
collections_12_mths_ex_med                                             178
policy_code                                                             33
application_type                                                        33
acc_now_delinq                                                          62
tot_coll_amt                                                         70309
tot_cur_bal                                                          70309
open_acc_6m                                                         866163
open_act_il                                                         866162
open_il_12m                                                         866162
open_il_24m                                                         866162
mths_since_rcnt_il                                                  909957
total_bal_il                                                        866162
il_util                                                            1068883
open_rv_12m                                                         866162
open_rv_24m                                                         866162
max_bal_bc                                                          866162
all_util                                                            866381
total_rev_hi_lim                                                     70309
inq_fi                                                              866162
total_cu_tl                                                         866163
inq_last_12m                                                        866163
acc_open_past_24mths                                                 50063
avg_cur_bal                                                          70379
bc_open_to_buy                                                       74968
bc_util                                                              76104
chargeoff_within_12_mths                                               178
delinq_amnt                                                             62
mo_sin_old_il_acct                                                  139104
mo_sin_old_rev_tl_op                                                 70310
mo_sin_rcnt_rev_tl_op                                                70310
mo_sin_rcnt_tl                                                       70309
mort_acc                                                             50063
mths_since_recent_bc                                                 73445
mths_since_recent_inq                                               295468
num_accts_ever_120_pd                                                70309
num_actv_bc_tl                                                       70309
num_actv_rev_tl                                                      70309
num_bc_sats                                                          58623
num_bc_tl                                                            70309
num_il_tl                                                            70309
num_op_rev_tl                                                        70309
num_rev_accts                                                        70310
num_rev_tl_bal_gt_0                                                  70309
num_sats                                                             58623
num_tl_120dpd_2m                                                    153690
num_tl_30dpd                                                         70309
num_tl_90g_dpd_24m                                                   70309
num_tl_op_past_12m                                                   70309
pct_tl_nvr_dlq                                                       70464
percent_bc_gt_75                                                     75412
pub_rec_bankruptcies                                                  1398
tax_liens                                                              138
tot_hi_cred_lim                                                      70309
total_bal_ex_mort                                                    50063
total_bc_limit                                                       50063
total_il_high_credit_limit                                           70309
hardship_flag                                                           33
disbursement_method                                                     33
debt_settlement_flag                                                    33
emp_length_int                                                           0
term_int                                                                33
earliest_cr_line_date                                                   62
mths_since_earliest_cr_line                                             62
issue_d_date                                                            33
mths_since_issue_d                                                      33
grade:A                                                                  0
grade:B                                                                  0
grade:C                                                                  0
grade:D                                                                  0
grade:E                                                                  0
grade:F                                                                  0
grade:G                                                                  0
sub_grade:A1                                                             0
sub_grade:A2                                                             0
sub_grade:A3                                                             0
sub_grade:A4                                                             0
sub_grade:A5                                                             0
sub_grade:B1                                                             0
sub_grade:B2                                                             0
sub_grade:B3                                                             0
sub_grade:B4                                                             0
sub_grade:B5                                                             0
sub_grade:C1                                                             0
sub_grade:C2                                                             0
sub_grade:C3                                                             0
sub_grade:C4                                                             0
sub_grade:C5                                                             0
sub_grade:D1                                                             0
sub_grade:D2                                                             0
sub_grade:D3                                                             0
sub_grade:D4                                                             0
sub_grade:D5                                                             0
sub_grade:E1                                                             0
sub_grade:E2                                                             0
sub_grade:E3                                                             0
sub_grade:E4                                                             0
sub_grade:E5                                                             0
sub_grade:F1                                                             0
sub_grade:F2                                                             0
sub_grade:F3                                                             0
sub_grade:F4                                                             0
sub_grade:F5                                                             0
sub_grade:G1                                                             0
sub_grade:G2                                                             0
sub_grade:G3                                                             0
sub_grade:G4                                                             0
sub_grade:G5                                                             0
home_ownership:ANY                                                       0
home_ownership:MORTGAGE                                                  0
home_ownership:NONE                                                      0
home_ownership:OTHER                                                     0
home_ownership:OWN                                                       0
home_ownership:RENT                                                      0
verification_status:Not Verified                                         0
verification_status:Source Verified                                      0
verification_status:Verified                                             0
loan_status:Charged Off                                                  0
loan_status:Current                                                      0
loan_status:Default                                                      0
loan_status:Does not meet the credit policy. Status:Charged Off          0
loan_status:Does not meet the credit policy. Status:Fully Paid           0
loan_status:Fully Paid                                                   0
loan_status:In Grace Period                                              0
loan_status:Late (16-30 days)                                            0
loan_status:Late (31-120 days)                                           0
purpose:car                                                              0
purpose:credit_card                                                      0
purpose:debt_consolidation                                               0
purpose:educational                                                      0
purpose:home_improvement                                                 0
purpose:house                                                            0
purpose:major_purchase                                                   0
purpose:medical                                                          0
purpose:moving                                                           0
purpose:other                                                            0
purpose:renewable_energy                                                 0
purpose:small_business                                                   0
purpose:vacation                                                         0
purpose:wedding                                                          0
addr_state:AK                                                            0
addr_state:AL                                                            0
addr_state:AR                                                            0
addr_state:AZ                                                            0
addr_state:CA                                                            0
addr_state:CO                                                            0
addr_state:CT                                                            0
addr_state:DC                                                            0
addr_state:DE                                                            0
addr_state:FL                                                            0
addr_state:GA                                                            0
addr_state:HI                                                            0
addr_state:IA                                                            0
addr_state:ID                                                            0
addr_state:IL                                                            0
addr_state:IN                                                            0
addr_state:KS                                                            0
addr_state:KY                                                            0
addr_state:LA                                                            0
addr_state:MA                                                            0
addr_state:MD                                                            0
addr_state:ME                                                            0
addr_state:MI                                                            0
addr_state:MN                                                            0
addr_state:MO                                                            0
addr_state:MS                                                            0
addr_state:MT                                                            0
addr_state:NC                                                            0
addr_state:ND                                                            0
addr_state:NE                                                            0
addr_state:NH                                                            0
addr_state:NJ                                                            0
addr_state:NM                                                            0
addr_state:NV                                                            0
addr_state:NY                                                            0
addr_state:OH                                                            0
addr_state:OK                                                            0
addr_state:OR                                                            0
addr_state:PA                                                            0
addr_state:RI                                                            0
addr_state:SC                                                            0
addr_state:SD                                                            0
addr_state:TN                                                            0
addr_state:TX                                                            0
addr_state:UT                                                            0
addr_state:VA                                                            0
addr_state:VT                                                            0
addr_state:WA                                                            0
addr_state:WI                                                            0
addr_state:WV                                                            0
addr_state:WY                                                            0
initial_list_status:f                                                    0
initial_list_status:w                                                    0
dtype: int64

## **1.Missing Values: Total Revolving limit & funded amount**

**A revolving limit** means you can finance and acquire equipment over an agreed timeframe, without the need to reapply each time you purchase a new asset.

***if the total revolving limit was missing, we will assume it is equal to the funded amount***

In [16]:
pd.options.display.max_rows=100

In [17]:
# first checking funded amount column and remove missing values, (funded_amnt):

data['funded_amnt'].isnull().sum()

33

In [18]:
# sine there is only 33 missing values compare to the total number of sample in the dataset those observation will be removed
data.dropna(subset=['funded_amnt'],inplace=True)

In [19]:
data.shape

(2260668, 242)

In [20]:
# now handling missing values in revolving limit by imputing values from funded amount columns
data['total_rev_hi_lim'].isnull().sum()

70276

In [21]:
data['total_rev_hi_lim'].fillna(data['funded_amnt'],inplace=True)

In [22]:
data['total_rev_hi_lim'].isnull().sum()

0

## **2. Missing Values: Annoul Income**

**Annual income** is the total amount of money made by the brower each year before deductions are taken out of your pay.

The missing values will be imputed by the average values on annoul income for other browers

In [23]:
data['annual_inc'].isnull().sum()

4

In [24]:
# first lets check and compare the values in the columns to pick one type of varage for na values:
data['annual_inc'].describe()

count    2.260664e+06
mean     7.799243e+04
std      1.126962e+05
min      0.000000e+00
25%      4.600000e+04
50%      6.500000e+04
75%      9.300000e+04
max      1.100000e+08
Name: annual_inc, dtype: float64

In [25]:
data['annual_inc'].mode()

0    60000.0
dtype: float64

In [26]:
data['annual_inc'].fillna((data['annual_inc'].mean()), inplace=True)

In [27]:
data['annual_inc'].isnull().sum()

0

## 3.Missing Values

following variables, replace the missing values with zeroes:

‘mths_since_earliest_cr_line’

‘acc_now_delinq’

‘total_acc’

‘pub_rec’

‘open_acc’

‘inq_last_6mths’

‘delinq_2yrs’

‘emp_length_int’

In [28]:
data[['mths_since_earliest_cr_line','acc_now_delinq','total_acc','pub_rec','open_acc','inq_last_6mths','delinq_2yrs','emp_length_int']].isnull().sum()

mths_since_earliest_cr_line    29
acc_now_delinq                 29
total_acc                      29
pub_rec                        29
open_acc                       29
inq_last_6mths                 30
delinq_2yrs                    29
emp_length_int                  0
dtype: int64

In [29]:
data[['mths_since_earliest_cr_line','acc_now_delinq','total_acc','pub_rec','open_acc','inq_last_6mths','delinq_2yrs','emp_length_int']]=data[['mths_since_earliest_cr_line','acc_now_delinq','total_acc','pub_rec','open_acc','inq_last_6mths','delinq_2yrs','emp_length_int']].fillna(0)

In [30]:
data[['mths_since_earliest_cr_line','acc_now_delinq','total_acc','pub_rec','open_acc','inq_last_6mths','delinq_2yrs','emp_length_int']].isnull().sum()

mths_since_earliest_cr_line    0
acc_now_delinq                 0
total_acc                      0
pub_rec                        0
open_acc                       0
inq_last_6mths                 0
delinq_2yrs                    0
emp_length_int                 0
dtype: int64

### checking missig values for all dataframe and removing all unnecesry variable

In [31]:
pd.options.display.max_rows=None
data.isnull().sum()

id                                                                       0
loan_amnt                                                                0
funded_amnt                                                              0
funded_amnt_inv                                                          0
term                                                                     0
int_rate                                                                 0
installment                                                              0
grade                                                                    0
sub_grade                                                                0
emp_title                                                           166969
emp_length                                                          146907
home_ownership                                                           0
annual_inc                                                               0
verification_status                                                      0
issue_d                                                                  0
loan_status                                                              0
pymnt_plan                                                               0
url                                                                      0
purpose                                                                  0
title                                                                23325
zip_code                                                                 1
addr_state                                                               0
dti                                                                   1711
delinq_2yrs                                                              0
earliest_cr_line                                                        29
fico_range_low                                                           0
fico_range_high                                                          0
inq_last_6mths                                                           0
mths_since_last_delinq                                             1158502
mths_since_last_record                                             1901512
open_acc                                                                 0
pub_rec                                                                  0
revol_bal                                                                0
revol_util                                                            1802
total_acc                                                                0
initial_list_status                                                      0
out_prncp                                                                0
out_prncp_inv                                                            0
total_pymnt                                                              0
total_pymnt_inv                                                          0
total_rec_prncp                                                          0
total_rec_int                                                            0
total_rec_late_fee                                                       0
recoveries                                                               0
collection_recovery_fee                                                  0
last_pymnt_d                                                          2427
last_pymnt_amnt                                                          0
last_credit_pull_d                                                      72
last_fico_range_high                                                     0
last_fico_range_low                                                      0
collections_12_mths_ex_med                                             145
policy_code                                                              0
application_type                                                         0
acc_now_delinq                                                           0
tot_coll_amt                                                         70276
tot_cur_bal                                                          70276
open_acc_6m                                                         866130
open_act_il                                                         866129
open_il_12m                                                         866129
open_il_24m                                                         866129
mths_since_rcnt_il                                                  909924
total_bal_il                                                        866129
il_util                                                            1068850
open_rv_12m                                                         866129
open_rv_24m                                                         866129
max_bal_bc                                                          866129
all_util                                                            866348
total_rev_hi_lim                                                         0
inq_fi                                                              866129
total_cu_tl                                                         866130
inq_last_12m                                                        866130
acc_open_past_24mths                                                 50030
avg_cur_bal                                                          70346
bc_open_to_buy                                                       74935
bc_util                                                              76071
chargeoff_within_12_mths                                               145
delinq_amnt                                                             29
mo_sin_old_il_acct                                                  139071
mo_sin_old_rev_tl_op                                                 70277
mo_sin_rcnt_rev_tl_op                                                70277
mo_sin_rcnt_tl                                                       70276
mort_acc                                                             50030
mths_since_recent_bc                                                 73412
mths_since_recent_inq                                               295435
num_accts_ever_120_pd                                                70276
num_actv_bc_tl                                                       70276
num_actv_rev_tl                                                      70276
num_bc_sats                                                          58590
num_bc_tl                                                            70276
num_il_tl                                                            70276
num_op_rev_tl                                                        70276
num_rev_accts                                                        70277
num_rev_tl_bal_gt_0                                                  70276
num_sats                                                             58590
num_tl_120dpd_2m                                                    153657
num_tl_30dpd                                                         70276
num_tl_90g_dpd_24m                                                   70276
num_tl_op_past_12m                                                   70276
pct_tl_nvr_dlq                                                       70431
percent_bc_gt_75                                                     75379
pub_rec_bankruptcies                                                  1365
tax_liens                                                              105
tot_hi_cred_lim                                                      70276
total_bal_ex_mort                                                    50030
total_bc_limit                                                       50030
total_il_high_credit_limit                                           70276
hardship_flag                                                            0
disbursement_method                                                      0
debt_settlement_flag                                                     0
emp_length_int                                                           0
term_int                                                                 0
earliest_cr_line_date                                                   29
mths_since_earliest_cr_line                                              0
issue_d_date                                                             0
mths_since_issue_d                                                       0
grade:A                                                                  0
grade:B                                                                  0
grade:C                                                                  0
grade:D                                                                  0
grade:E                                                                  0
grade:F                                                                  0
grade:G                                                                  0
sub_grade:A1                                                             0
sub_grade:A2                                                             0
sub_grade:A3                                                             0
sub_grade:A4                                                             0
sub_grade:A5                                                             0
sub_grade:B1                                                             0
sub_grade:B2                                                             0
sub_grade:B3                                                             0
sub_grade:B4                                                             0
sub_grade:B5                                                             0
sub_grade:C1                                                             0
sub_grade:C2                                                             0
sub_grade:C3                                                             0
sub_grade:C4                                                             0
sub_grade:C5                                                             0
sub_grade:D1                                                             0
sub_grade:D2                                                             0
sub_grade:D3                                                             0
sub_grade:D4                                                             0
sub_grade:D5                                                             0
sub_grade:E1                                                             0
sub_grade:E2                                                             0
sub_grade:E3                                                             0
sub_grade:E4                                                             0
sub_grade:E5                                                             0
sub_grade:F1                                                             0
sub_grade:F2                                                             0
sub_grade:F3                                                             0
sub_grade:F4                                                             0
sub_grade:F5                                                             0
sub_grade:G1                                                             0
sub_grade:G2                                                             0
sub_grade:G3                                                             0
sub_grade:G4                                                             0
sub_grade:G5                                                             0
home_ownership:ANY                                                       0
home_ownership:MORTGAGE                                                  0
home_ownership:NONE                                                      0
home_ownership:OTHER                                                     0
home_ownership:OWN                                                       0
home_ownership:RENT                                                      0
verification_status:Not Verified                                         0
verification_status:Source Verified                                      0
verification_status:Verified                                             0
loan_status:Charged Off                                                  0
loan_status:Current                                                      0
loan_status:Default                                                      0
loan_status:Does not meet the credit policy. Status:Charged Off          0
loan_status:Does not meet the credit policy. Status:Fully Paid           0
loan_status:Fully Paid                                                   0
loan_status:In Grace Period                                              0
loan_status:Late (16-30 days)                                            0
loan_status:Late (31-120 days)                                           0
purpose:car                                                              0
purpose:credit_card                                                      0
purpose:debt_consolidation                                               0
purpose:educational                                                      0
purpose:home_improvement                                                 0
purpose:house                                                            0
purpose:major_purchase                                                   0
purpose:medical                                                          0
purpose:moving                                                           0
purpose:other                                                            0
purpose:renewable_energy                                                 0
purpose:small_business                                                   0
purpose:vacation                                                         0
purpose:wedding                                                          0
addr_state:AK                                                            0
addr_state:AL                                                            0
addr_state:AR                                                            0
addr_state:AZ                                                            0
addr_state:CA                                                            0
addr_state:CO                                                            0
addr_state:CT                                                            0
addr_state:DC                                                            0
addr_state:DE                                                            0
addr_state:FL                                                            0
addr_state:GA                                                            0
addr_state:HI                                                            0
addr_state:IA                                                            0
addr_state:ID                                                            0
addr_state:IL                                                            0
addr_state:IN                                                            0
addr_state:KS                                                            0
addr_state:KY                                                            0
addr_state:LA                                                            0
addr_state:MA                                                            0
addr_state:MD                                                            0
addr_state:ME                                                            0
addr_state:MI                                                            0
addr_state:MN                                                            0
addr_state:MO                                                            0
addr_state:MS                                                            0
addr_state:MT                                                            0
addr_state:NC                                                            0
addr_state:ND                                                            0
addr_state:NE                                                            0
addr_state:NH                                                            0
addr_state:NJ                                                            0
addr_state:NM                                                            0
addr_state:NV                                                            0
addr_state:NY                                                            0
addr_state:OH                                                            0
addr_state:OK                                                            0
addr_state:OR                                                            0
addr_state:PA                                                            0
addr_state:RI                                                            0
addr_state:SC                                                            0
addr_state:SD                                                            0
addr_state:TN                                                            0
addr_state:TX                                                            0
addr_state:UT                                                            0
addr_state:VA                                                            0
addr_state:VT                                                            0
addr_state:WA                                                            0
addr_state:WI                                                            0
addr_state:WV                                                            0
addr_state:WY                                                            0
initial_list_status:f                                                    0
initial_list_status:w                                                    0
dtype: int64

In [32]:
# Drop most of unnacess
data.drop(['open_acc_6m','open_act_il','open_il_12m','open_il_24m','mths_since_rcnt_il','total_bal_il','il_util','open_rv_12m',
           'open_rv_24m','max_bal_bc','all_util','inq_fi','total_cu_tl','inq_last_12m','acc_open_past_24mths','avg_cur_bal','bc_open_to_buy','bc_util',
           'chargeoff_within_12_mths','delinq_amnt','mo_sin_old_il_acct','mo_sin_old_rev_tl_op','mo_sin_rcnt_rev_tl_op','mo_sin_rcnt_tl','mort_acc',
           'mths_since_recent_bc','mths_since_recent_inq','num_accts_ever_120_pd','num_actv_bc_tl','num_actv_rev_tl','num_bc_sats','num_bc_tl','num_il_tl',
           'num_op_rev_tl','num_rev_accts','num_rev_tl_bal_gt_0','num_sats','num_tl_120dpd_2m','num_tl_30dpd','num_tl_90g_dpd_24m','num_tl_op_past_12m',
           'pct_tl_nvr_dlq','percent_bc_gt_75','pub_rec_bankruptcies','tax_liens','tot_hi_cred_lim','total_bal_ex_mort',
           'total_bc_limit','total_il_high_credit_limit'], axis = 1,inplace=True)

In [33]:

data.isnull().sum()

id                                                                       0
loan_amnt                                                                0
funded_amnt                                                              0
funded_amnt_inv                                                          0
term                                                                     0
int_rate                                                                 0
installment                                                              0
grade                                                                    0
sub_grade                                                                0
emp_title                                                           166969
emp_length                                                          146907
home_ownership                                                           0
annual_inc                                                               0
verification_status                                                      0
issue_d                                                                  0
loan_status                                                              0
pymnt_plan                                                               0
url                                                                      0
purpose                                                                  0
title                                                                23325
zip_code                                                                 1
addr_state                                                               0
dti                                                                   1711
delinq_2yrs                                                              0
earliest_cr_line                                                        29
fico_range_low                                                           0
fico_range_high                                                          0
inq_last_6mths                                                           0
mths_since_last_delinq                                             1158502
mths_since_last_record                                             1901512
open_acc                                                                 0
pub_rec                                                                  0
revol_bal                                                                0
revol_util                                                            1802
total_acc                                                                0
initial_list_status                                                      0
out_prncp                                                                0
out_prncp_inv                                                            0
total_pymnt                                                              0
total_pymnt_inv                                                          0
total_rec_prncp                                                          0
total_rec_int                                                            0
total_rec_late_fee                                                       0
recoveries                                                               0
collection_recovery_fee                                                  0
last_pymnt_d                                                          2427
last_pymnt_amnt                                                          0
last_credit_pull_d                                                      72
last_fico_range_high                                                     0
last_fico_range_low                                                      0
collections_12_mths_ex_med                                             145
policy_code                                                              0
application_type                                                         0
acc_now_delinq                                                           0
tot_coll_amt                                                         70276
tot_cur_bal                                                          70276
total_rev_hi_lim                                                         0
hardship_flag                                                            0
disbursement_method                                                      0
debt_settlement_flag                                                     0
emp_length_int                                                           0
term_int                                                                 0
earliest_cr_line_date                                                   29
mths_since_earliest_cr_line                                              0
issue_d_date                                                             0
mths_since_issue_d                                                       0
grade:A                                                                  0
grade:B                                                                  0
grade:C                                                                  0
grade:D                                                                  0
grade:E                                                                  0
grade:F                                                                  0
grade:G                                                                  0
sub_grade:A1                                                             0
sub_grade:A2                                                             0
sub_grade:A3                                                             0
sub_grade:A4                                                             0
sub_grade:A5                                                             0
sub_grade:B1                                                             0
sub_grade:B2                                                             0
sub_grade:B3                                                             0
sub_grade:B4                                                             0
sub_grade:B5                                                             0
sub_grade:C1                                                             0
sub_grade:C2                                                             0
sub_grade:C3                                                             0
sub_grade:C4                                                             0
sub_grade:C5                                                             0
sub_grade:D1                                                             0
sub_grade:D2                                                             0
sub_grade:D3                                                             0
sub_grade:D4                                                             0
sub_grade:D5                                                             0
sub_grade:E1                                                             0
sub_grade:E2                                                             0
sub_grade:E3                                                             0
sub_grade:E4                                                             0
sub_grade:E5                                                             0
sub_grade:F1                                                             0
sub_grade:F2                                                             0
sub_grade:F3                                                             0
sub_grade:F4                                                             0
sub_grade:F5                                                             0
sub_grade:G1                                                             0
sub_grade:G2                                                             0
sub_grade:G3                                                             0
sub_grade:G4                                                             0
sub_grade:G5                                                             0
home_ownership:ANY                                                       0
home_ownership:MORTGAGE                                                  0
home_ownership:NONE                                                      0
home_ownership:OTHER                                                     0
home_ownership:OWN                                                       0
home_ownership:RENT                                                      0
verification_status:Not Verified                                         0
verification_status:Source Verified                                      0
verification_status:Verified                                             0
loan_status:Charged Off                                                  0
loan_status:Current                                                      0
loan_status:Default                                                      0
loan_status:Does not meet the credit policy. Status:Charged Off          0
loan_status:Does not meet the credit policy. Status:Fully Paid           0
loan_status:Fully Paid                                                   0
loan_status:In Grace Period                                              0
loan_status:Late (16-30 days)                                            0
loan_status:Late (31-120 days)                                           0
purpose:car                                                              0
purpose:credit_card                                                      0
purpose:debt_consolidation                                               0
purpose:educational                                                      0
purpose:home_improvement                                                 0
purpose:house                                                            0
purpose:major_purchase                                                   0
purpose:medical                                                          0
purpose:moving                                                           0
purpose:other                                                            0
purpose:renewable_energy                                                 0
purpose:small_business                                                   0
purpose:vacation                                                         0
purpose:wedding                                                          0
addr_state:AK                                                            0
addr_state:AL                                                            0
addr_state:AR                                                            0
addr_state:AZ                                                            0
addr_state:CA                                                            0
addr_state:CO                                                            0
addr_state:CT                                                            0
addr_state:DC                                                            0
addr_state:DE                                                            0
addr_state:FL                                                            0
addr_state:GA                                                            0
addr_state:HI                                                            0
addr_state:IA                                                            0
addr_state:ID                                                            0
addr_state:IL                                                            0
addr_state:IN                                                            0
addr_state:KS                                                            0
addr_state:KY                                                            0
addr_state:LA                                                            0
addr_state:MA                                                            0
addr_state:MD                                                            0
addr_state:ME                                                            0
addr_state:MI                                                            0
addr_state:MN                                                            0
addr_state:MO                                                            0
addr_state:MS                                                            0
addr_state:MT                                                            0
addr_state:NC                                                            0
addr_state:ND                                                            0
addr_state:NE                                                            0
addr_state:NH                                                            0
addr_state:NJ                                                            0
addr_state:NM                                                            0
addr_state:NV                                                            0
addr_state:NY                                                            0
addr_state:OH                                                            0
addr_state:OK                                                            0
addr_state:OR                                                            0
addr_state:PA                                                            0
addr_state:RI                                                            0
addr_state:SC                                                            0
addr_state:SD                                                            0
addr_state:TN                                                            0
addr_state:TX                                                            0
addr_state:UT                                                            0
addr_state:VA                                                            0
addr_state:VT                                                            0
addr_state:WA                                                            0
addr_state:WI                                                            0
addr_state:WV                                                            0
addr_state:WY                                                            0
initial_list_status:f                                                    0
initial_list_status:w                                                    0
dtype: int64

# Preprocessing the Dependant Variable (Target)

In [34]:
data['loan_status'].value_counts()

Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
Name: loan_status, dtype: int64

In [ ]:
data['loan_status'].value_counts()/data['loan_status'].count()

Fully Paid                                             0.476298
Current                                                0.388521
Charged Off                                            0.118796
Late (31-120 days)                                     0.009496
In Grace Period                                        0.003732
Late (16-30 days)                                      0.001924
Does not meet the credit policy. Status:Fully Paid     0.000879
Does not meet the credit policy. Status:Charged Off    0.000337
Default                                                0.000018
Name: loan_status, dtype: float64

In [ ]:
data['Non-Default_Default']=np.where(data['loan_status'].isin(['Charged Off','Default','Does not meet the credit policy. Status:Charged Off','Late (31-120 days)']),0,1)

In [ ]:
data['Non-Default_Default'].value_counts()

1    1969841
0     290827
Name: Non-Default_Default, dtype: int64

In [ ]:
data[['Non-Default_Default','loan_status']].sample(5)

         Non-Default_Default loan_status
1354346                    1     Current
1508009                    1     Current
562400                     1  Fully Paid
2053951                    1     Current
1896031                    1  Fully Paid

## Lastly balancing the data according to the target Variable

In [ ]:
# Checking the number of sample for each class before balancing
data['Non-Default_Default'].value_counts()

1    1969841
0     290827
Name: Non-Default_Default, dtype: int64

Since there are more than 2 million sample **downsampling** is sutiable for the dataset

In [ ]:
# Creating Function for Dwonsampling
def downsample(df:pd.DataFrame, label_col_name:str) -> pd.DataFrame:
    # find the number of observations in the smallest group
    nmin = df[label_col_name].value_counts().min()
    return (df
            # split the dataframe per group
            .groupby(label_col_name)
            # sample nmin observations from each group
            .apply(lambda x: x.sample(nmin))
            # recombine the dataframes
            .reset_index(drop=True)
            )

In [ ]:
data=downsample(data,label_col_name='Non-Default_Default')

In [ ]:
data['Non-Default_Default'].value_counts()

1    290827
0    290827
Name: Non-Default_Default, dtype: int64

Now we have equal number of sample for both classes

In [ ]:
data[['Non-Default_Default','loan_status']].sample(5)

        Non-Default_Default  loan_status
293137                    1      Current
76415                     0  Charged Off
144220                    0  Charged Off
110873                    0  Charged Off
579290                    1      Current

In [ ]:
data.shape

(581654, 194)

In [ ]:
data.to_csv('data_2.csv',index=False)